name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      parallel:
        description: 'Run tests in parallel? (true/false)'
        required: true
        default: 'false'
        type: boolean


jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run unit tests
        run: |
          cd ../../../testing/test/src/tests
          if [[ "${{ inputs.parallel }}" == "true" ]]; then
            pytest -n auto --alluredir=allure-results user_tests.py product_tests.py product_cart_tests.py product_order_tests.py payment_tests.py order_tests.py cart_tests.py
          else
            pytest --alluredir=allure-results user_tests.py product_tests.py product_cart_tests.py product_order_tests.py payment_tests.py order_tests.py cart_tests.py
          fi
